# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-14 17:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu_planning_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecipe',
            name='category',
            field=models.CharField(default='uncategorized', max_length=100),
        ),
        migrations.AlterField(
            model_name='userrecipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_recipe', to='menu_planning_app.Recipe'),
        ),
        migrations.AlterField(
            model_name='userrecipe',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_recipe', to='login_reg_app.User'),
        ),
    ]
