# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_planning_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='photo',
            field=models.CharField(default='../static/images/default.jpg', max_length=1000),
        ),
    ]
