# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-14 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_planning_app', '0002_auto_20170514_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecipe',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
