# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_planning_app', '0003_auto_20170328_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='publisher',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
