# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg_app', '0006_auto_20170329_2040'),
        ('menu_planning_app', '0004_recipe_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='users',
            field=models.ManyToManyField(related_name='recipes', to='login_reg_app.User'),
        ),
    ]
