# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 20:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='admin_level',
        ),
        migrations.RemoveField(
            model_name='user',
            name='description',
        ),
    ]
