# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 17:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg_app', '0002_auto_20170323_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hired',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
