# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 20:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg_app', '0004_auto_20170324_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
